/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cucumber.selenium;

public class App {

    public static void main(String[] args) throws InterruptedException {

    }
}
