/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bdd.tax.calculation;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class TaxCalculationApp {

    public static void main(String[] args) {
        SpringApplication.run(TaxCalculationApp.class, args);
    }
}
